### ISSUE TITLE
Improving README.md

### ISSUE THREAD

**Issue by Ryuno-Ki** [pitchmuc/pylaunch#2]
Hi Julien,

have you thought about [turning your README into an awesome one](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)?

**Comment by pitchmuc** [comment]
Yes. I have thought of this but for this weekend project, I felt that it was not necessary.
Especially as there are lots of content for it on my blog.
For the mktcloud pypi module that I plan to create, I will probably improve all of that. :)
