### ISSUE TITLE
Add a linter

### ISSUE THREAD

**Issue by Ryuno-Ki** [pitchmuc/pylaunch#4]
Hi Julien,

have you thought about adding a linter like [pylint](https://www.pylint.org/), [flake8](https://gitlab.com/pycqa/flake8) or [black](https://black.readthedocs.io/en/stable/)?

**Comment by pitchmuc** [comment]
I need to research that ! Thanks for the links. 
I see that most of the projects has one. I am not familiar with them yet but it would be very useful for debugging as I saw it.

**Comment by VikashKotharyWork** [comment]
I'm not sure why this was closed, but I'm happy to help out if there's still interest.
