### ISSUE TITLE
Add ReadTheDocs

### ISSUE THREAD

**Issue by Ryuno-Ki** [pitchmuc/pylaunch#6]
Hi Julien,

in the presentation you gave today, you have highlighted, that you are documenting your code.
That's great!

Have you considered [pushing it to readthedocs.io](https://readthedocs.org/)?

**Comment by pitchmuc** [comment]
Mostly the documentation is hosted on https://www.datanalyst.info/ and for this one, especially on this one : https://www.datanalyst.info/category/python/launch-api/

**Comment by VikashKotharyWork** [comment]
Mind adding it to the README.md to making it easier to find for newbies?
