### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by Ryuno-Ki** [pitchmuc/pylaunch#7]
Hi Julien,

I've noted, that this project is not on PyPi, yet.
If you need help [I scribbled down something on my blog](https://jaenis.ch/hobbies/coding/cheatsheets/python/).

**Comment by pitchmuc** [comment]
hey Andre, 
Sorry for some reason I was not listening to my own project issues. :) 
Thanks for the blog post, I definitely would need to do some researched on how to publish it.

**Comment by Ryuno-Ki** [comment]
Luckily GitHub isn't running away :-D

**Comment by VikashKotharyWork** [comment]
I've created a PR to use poetry to build and publish this library. I find the process is a lot simpler compared to the traditional setup.py and has a lot of advantages ootb. What do you guys things @pitchmuc @Ryuno-Ki ?

**Comment by Ryuno-Ki** [comment]
I'm neither using Make nor Poetry.

**Comment by VikashKotharyWork** [comment]
So you should be able to use it the same as the traditional `pip install` when using the library. Just wanted to know if there were any advantages of using the traditional publishing method as shown in your blog. 

Once my PR is merged, you'll also be able to do `pip install git+https://github.com/pitchmuc/pylaunch.git`

**Comment by pitchmuc** [comment]
I have now updated that project and published it to pypi. 
Changed the name of the module though because pylaunch was already taken. 
Thanks for your help guys.

**Comment by VikashKotharyWork** [comment]
Is there a reason you haven't added your `setup.py` or `pyproject.toml` to the repo?

**Comment by pitchmuc** [comment]
None. I just didn't think it would interest someone.
I'll add it.
